// This code was generated by a tool (MethodCache.tt).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Concurrent;
using System.Reflection;

namespace NeatMapper.EntityFrameworkCore {
	internal sealed class MethodCacheAction<TKey> 
#if NETCOREAPP3_1 || NET5_0_OR_GREATER
		where TKey : notnull
#endif
		{
		private readonly ConcurrentDictionary<TKey, Action> _cache =
			new ConcurrentDictionary<TKey, Action>();

		private readonly Func<TKey, MethodInfo> _methodSelector;
		private readonly Func<TKey> _keySelector;
		private readonly string[] _parameterNames;


		public MethodCacheAction(Func<TKey> keySelector, Func<TKey, MethodInfo> methodSelector, params string[] parameterNames) {
			_methodSelector = methodSelector;
			_keySelector = keySelector;
			_parameterNames = parameterNames;
		}

		public void Invoke() {
			_cache.GetOrAdd(_keySelector.Invoke(), k =>
				NeatMapper.TypeUtils.MethodToDelegate<Action>(_methodSelector.Invoke(k), null, _parameterNames))
					.Invoke();
		}
	}

	internal sealed class MethodCacheAction<TKey, TArg0> 
#if NETCOREAPP3_1 || NET5_0_OR_GREATER
		where TKey : notnull
#endif
		{
		private readonly ConcurrentDictionary<TKey, Action<TArg0>> _cache =
			new ConcurrentDictionary<TKey, Action<TArg0>>();

		private readonly Func<TKey, MethodInfo> _methodSelector;
		private readonly Func<TArg0, TKey> _keySelector;
		private readonly string[] _parameterNames;


		public MethodCacheAction(Func<TArg0, TKey> keySelector, Func<TKey, MethodInfo> methodSelector, params string[] parameterNames) {
			_methodSelector = methodSelector;
			_keySelector = keySelector;
			_parameterNames = parameterNames;
		}

		public void Invoke(TArg0 arg0) {
			_cache.GetOrAdd(_keySelector.Invoke(arg0), k =>
				NeatMapper.TypeUtils.MethodToDelegate<Action<TArg0>>(_methodSelector.Invoke(k), null, _parameterNames))
					.Invoke(arg0);
		}
	}

}