name: Build test and publish packages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: 
    - "src/**"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build all projects
        run: dotnet build --configuration Release
      - name: Test all projects
        run: dotnet test --configuration Release --no-build

  deploy:
    environment:
      name: nuget
    runs-on: windows-latest
    needs: build
    steps:
      - name: Publish NeatMapper core to Nuget
        run: dotnet nuget push "src/NeatMapper/bin/Release/*.symbols.nupkg" -sk ${{ secrets.API_KEY }}
      - name: Publish NeatMapper EF Core to Nuget
        run: dotnet nuget push "src/NeatMapper.EntityFrameworkCore/bin/Release/*.symbols.nupkg" -sk ${{ secrets.API_KEY }}
      - name: Publish NeatMapper Transitive to Nuget
        run: dotnet nuget push "src/NeatMapper.Transitive/bin/Release/*.symbols.nupkg" -sk ${{ secrets.API_KEY }}
      
